CREATE DATABASE [Balta]

CREATE TABLE [Student](
    [Id] UNIQUEIDENTIFIER NOT NULL,
    [Name] NVARCHAR(120) NOT NULL,
    [Email] NVARCHAR(180) NOT NULL,
    [Document] NVARCHAR(20) NULL,
    [Phone] NVARCHAR(20) NULL,
    [Birthdate] DATETIME NULL,
    [Createdate] DATETIME NOT NULL,
    CONSTRAINT [PK_Student] PRIMARY KEY ([Id])
);