CREATE DATABASE [Cursos]

GO
USE [Cursos]
CREATE TABLE [Categoria](
    [ID] INT NOT NULL IDENTITY(1, 1),
    [NAME] VARCHAR(80),
    CONSTRAINT [PK_Categoria] PRIMARY KEY([ID])
)
GO
DROP TABLE [Curso]
CREATE TABLE [Curso](
    [ID] INT NOT NULL IDENTITY(1, 1),
    [NAME] VARCHAR(80),
    [CATEGORIAID] INT NOT NULL,
    CONSTRAINT [PK_Curso] PRIMARY KEY([ID]),
    CONSTRAINT [FK_Curso] FOREIGN KEY([CATEGORIAID])
    REFERENCES [Categoria]([ID])
   
)
GO
