INSERT INTO[Categoria]([NAME]) VALUES('BACKEND')
INSERT INTO[Categoria]([NAME]) VALUES('FRONT-END')

INSERT INTO [Curso]([NAME],[CATEGORIAID]) VALUES('Fundamentos OOP', 1) 
INSERT INTO [Curso]([NAME],[CATEGORIAID]) VALUES('Fundamentos C#', 1) 
INSERT INTO [Curso]([NAME],[CATEGORIAID]) VALUES('Angular', 2) 