CREATE OR ALTER PROCEDURE [LINDOJOAO] AS 
DECLARE @CategoriaID INT
SET @CategoriaID = (SELECT TOP 1 [ID] FROM [Categoria] WHERE [NAME] = 'Backend')
SELECT * FROM [Curso] WHERE [CATEGORIAID] = @CategoriaID