USE [Curso]

DROP TABLE [Aluno]
CREATE TABLE [Aluno](
    [ID] INT,
    [NAME] VARCHAR(80),
    [NASCIMENTO] DATETIME,
    [ACTIVE] BIT,
    [Nome] VARCHAR(100) NOT NULL UNIQUE,
    PRIMARY KEY ([ID])
)
GO
CREATE TABLE [Curso](
    [ID] INT,
    [NAME] VARCHAR(80),
    CONSTRAINT [PK_Curso] PRIMARY KEY([ID])
)
GO
CREATE TABLE [ProgressoCurso](
    [ALUNOID] INT NOT NULL,
    [CURSOID] INT NOT NULL,
    [PROGRESSO] INT NOT NULL,
    [ULTIMAATUALIZACAO] DATETIME NOT NULL DEFAULT(GETDATE()),
)
GO

